
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: shine
  password: shine

  pool: 5

development:
  <<: *default
  database: shine_development


test:
  <<: *default
  database: shine_test


